services:
  ejabberd:
    image: ejabberd/ecs:latest
    container_name: ejabberd
    hostname: ejabberd
    restart: unless-stopped

    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"

    volumes:
      - ./conf:/opt/ejabberd/conf
      - ./database:/opt/ejabberd/database
      - ./logs:/opt/ejabberd/logs
      - ./upload:/opt/ejabberd/upload